### PR TITLE
readWriteCloser#Read(): add timestamp to frame

### LINKED ISSUE #3: add time stamp to received frames
Hi there,

I would love to get time stamps of received CAN frames as accurate as possible. At least for Linux it should be possible.

From Linux SocketCAN documentation:

> An accurate timestamp can be obtained with an ioctl(2) call after reading  a message from the socket:

    struct timeval tv;
    ioctl(s, SIOCGSTAMP, &tv);

PR follows.

Regards, Stephan

### PR DESCRIPTION
**Pull request by skladd**
should fix #3 

tested on Linux x86_64 and armv7l

### CODE REVIEW

**Comment by brutella** [comment]
`syscall.SIOCGSTAMP` is only available on linux and solaris platforms – see https://golang.org/search?q=SIOCGSTAMP#Textual

Have you tried to use the socket option `syscall.SO_TIMESTAMP` already? This should work on more platforms?

**Comment by skladd** [comment]
Thanks for taking a look.
Setting the socket option is the easy part, but I have to receive the socket control messages containing the timestamps. This means we have to use `syscall.Recvmsg` on the socket instead of `rwc.Read`.
I got it working now, I will commit it tomorrow after cleaning up. Nevertheless, the current tests will fail, I guess.

**Comment by skladd** [comment]
These are quite big changes IMHO... Do you know a better way to get the timestamps on all supported platforms? Does it work on Darwin?

**Comment by skladd** [comment]
It doesn't work on my arm board, syscall.ParseSocketControlMessage(oob) returns an error there (0x16 EINVAL "invalid argument"), apparently coming from socketControlMessageHeaderAndData() in /usr/local/go/src/syscall/sockcmsg_unix.go.
I will have a look at it...

**Comment by skladd** [comment]
@brutella, I finally got back to this. It now works for me on both x86_64 and arm Linux. Could you please test it?

**Comment by skladd** [comment]
I finally decided to use my fork

**Pull request closed without merging**
